### ISSUE TITLE
Update selenium and chrome issues to latest version

### ISSUE THREAD

**Issue by omarlopesino** [Metadrop/drupal-boilerplate#101]
Currently boilerplate uses the version 4.1.3 of hub and chrome, but there exists a 4.8.0 version. I've tried to use it in a specific project, but I've got this error:

![imagen](https://user-images.githubusercontent.com/3202817/218499494-8e73b6bf-ad15-48bc-842d-407112ad10ac.png)

That error blocks from upgrading the image versions.

This issue is opened to manage the upgrade and the possible errors.

**Comment by rsanzante** [comment]
We have been using 4.8.0 in several projects and we didn't find any issue, as far as I know. The image has been updated in https://github.com/Metadrop/drupal-boilerplate/commit/2fdcac3561a76ab2db2fb993eee30e4f4e2fc3ac

I'm closing this because it is already updated. However, we can reopen it it we detect the commented issue.
