### ISSUE TITLE
Version 1.2.2 requires a file from 2.x

### ISSUE THREAD

**Issue by idiazroncero** [Metadrop/drupal-boilerplate#67]
**Steps to reproduce**

- Run `composer create-project  --ignore-platform-reqs metadrop/drupal-boilerplate myproject`
- Version 1.2.2 will be used: `Installing metadrop/drupal-boilerplate (v1.2.2): Extracting archive`
- After confirming the project name, the following error will appear:

```
Setting up .env file
Setting up Drush aliases file

                                                                                                                
  [ErrorException]                                                                                              
  file_get_contents(./drush/sites/sitename.site.yml.example): Failed to open stream: No such file or directory  
```   

And yes, the `sitename.site.yml.example` is a file that seems to be present on the 2.x branch [but not on the 1.x](https://github.com/Metadrop/drupal-boilerplate/tree/v1.2.2). It seems to be a leak from 2.x development back into the 1.x branch.

**Comment by rsanzante** [comment]
Confirmed!

The problem is related to metadrop/drupal-dev and Scripthor. Scripthor, since [this commit,](https://github.com/Metadrop/scripthor/commit/cb07b8a776a7bc795cf37896a50287c5fb7e95e1), expects a sitename.site.yml file that is only in the 2.x boilerplate.

The solution is to restrict the Scripthor version in the boielrplate 1.x. To do this, we need to restrict metadrop/drupal-dev because is the package that requires Scripthor (the boilerplate includes Scripthor through metadrop/drupal-dev).

**Comment by rsanzante** [comment]
Fixed! New release 1.2.3 created.

Thanks!

**Comment by rsanzante** [comment]
However, it is better to use the 2.x branch. I'm creating a stable release for the 2.x.

**Comment by idiazroncero** [comment]
Glad to see 2.x becoming stable!
